// <auto-generated />
namespace PostsPortal.Migrations.CAMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Ajmajtfaktingzaphir : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajmajtfaktingzaphir));
        
        string IMigrationMetadata.Id
        {
            get { return "201809142147161_Aj majt fak tingz ap hir"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
